language: node_js
node_js:
  - "5"
  - "4.2.1"

script:
  - npm install
  - npm run-script test-travis

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
